# Site settings
title: Dropwizard Modules Directory
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://modules.dropwizard.io" # the base hostname & protocol for your site
twitter_username: dropwizardio
github_username:  dropwizard

# Build settings
markdown: kramdown

# SEO settings
twitter:
  username: "dropwizardio"
description: "A directory of extension modules for Dropwizard."
google_site_verification: "3pF8PzUuOrtxjUqU8FX00DiUTwx7K98DXZAsrZeK63A"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
